<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Ejercicio 3</title>
    <link rel="stylesheet" href="../css/style.css" />
  </head>
  <body>
    <h1>Ejercicio 3</h1>
    <p>
      Ej3: Sobre el código anterior añade un manejo de errores utilizando catch
      y muestra un mensaje como "Error al cargar los datos" en la página si
      falla. Puedes verificar la propiedad response.ok para saber si la
      solicitud fue exitosa. Para probarlo modifica la url por una que no
      exista.
    </p>
    <button onclick="window.location.href='../index.html'">Volver</button>
    <ul id="lista"></ul>
    <p id="error"></p>

    <script>
      async function obtenerUsuarios(params) {
        try {
          const response = await fetch("https://reqrees.in/api/users?page=1");
          if (!response.ok) {
            throw new Error(`Error HTTP: ${response.status}`);
          }
          const usuarios = await response.json();
          const lista = document.getElementById("lista");
          usuarios.data.forEach((usuario) => {
            const nuevaLinea = document.createElement("li");
            nuevaLinea.textContent = `Nombre: ${usuario.first_name} Email: ${usuario.email}`;
            lista.appendChild(nuevaLinea);
          });
        } catch (error) {
          document.getElementById("error").textContent =
            "Error al cargar los datos: " + error.message;
          console.error("Error: ", error.message);
        }
      }

      obtenerUsuarios();
    </script>
  </body>
</html>
